language: java
script: ant -f linux/build.xml
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tidy javahelp2 zlib1g-dev libjpeg-dev libxmu-dev libglu1-mesa-dev freeglut3-dev libxi-dev liblzma-dev liblcms2-dev autoconf automake libtool nasm
